ALTER TABLE contest_participants
    MODIFY COLUMN status VARCHAR(20) NOT NULL DEFAULT 'REGISTERED';

ALTER TABLE contest_participants
    MODIFY COLUMN joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;